--- 
- name: Install Osticket
  hosts: localhost
  vars:
    docker_ctx: "{{inventory_dir }}/../docker"
  roles:
    - osticket
  tasks:
    - debug:
        var: docker_ctx

    - name: Install "docker-compose.yml" 
      copy:
        src: etc/docker-compose.yml
        dest: "{{ docker_ctx }}/etc/osticket/docker-compose.yml"
        mode: 0644

    - name: Setup env
      copy:
        src: etc/env.cfg
        dest: "{{ docker_ctx }}/etc/osticket/env/.envosticket"
        mode: 0640
  
