--- 
- name: Install Osticket
  hosts: localhost
  vars:
    docker_ctx: "{{inventory_dir }}/../docker"
  roles:
    - osticket
  tasks:
    - debug:
        var: docker_ctx

    - name: Setup env
      copy:
        src: docker/etc/osticket/env/dev/envosticket
        dest: "{{ docker_ctx }}/etc/osticket/env/.envosticket"
        mode: 0640
  
